[package]
name = "myco-html-rewriter"
version = "0.0.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
myco = { path = "../myco" }
futures-lite = "1.11.3"
lol-async = { git = "https://github.com/jbr/lol-async", branch = "main" }
async-global-executor = "2.0.2"

[dev-dependencies]
myco-smol-server = { path = "../smol-server" }
myco-proxy = { path = "../proxy" }
env_logger = "0.8.3"
